version: '3.4'

services:
  adminapi:
    image: ${DOCKER_REGISTRY-}adminapi
    build:
      context: .
      dockerfile: AdminApi/Dockerfile
    external_links:
      - mamongo
      - tenantapi
        

  tenantapi:
    image: ${DOCKER_REGISTRY-}tenantapi
    build:
      context: .
      dockerfile: TenantApi/Dockerfile
    external_links:
      - mamongo
      - adminapi

  mamongo:
    image: mongo:latest
    volumes:
     - mavolume:/data/db
    
volumes:
  mavolume:

networks:
  multiapinetwork:
    external: true
    
    
