version: '3.4'

services:
  adminapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9001:80"

  tenantapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9002:80"

  mamongo:
    ports:
      - "40000:27017"

