version: '3.4'

services:
  adminapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  tenantapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
